dist: bionic
language: java
before_install:
  - rm ~/.m2/settings.xml
jdk:
  - openjdk11
env:
  global:
    - secure: "do2hiMNTdOjnLcDMtFJxa8WqSR+VLA1773qbaJBVm6+h0qFAsYBw71aKBrkmcCxprbU4QJiqK0pp54vd5AOTLUZZ1Auh1PBhN1TQQgJbn3Z9ltZBqCS8sP9DwNgvaUOU2CStPkGkEtGB/DhcHGVJeWiCYMj/CJbzsfFcd4pBnN/yWG8BE0k1s9V3uFwzizp72el+RK4tpG2yg/1vqPezsOtXvb/MSBy8D9EsK89GhWsFQ21QpvPLTAujjTnAKZZA/mILIyo23IKNtIF064pt+mvIzhxRbOcH28Qgf8/Dq7mWyn2kX0vaC+YQ8COyPyCWqRQjikvWvieWtb0i3tFqge8yz9Q8JY5uKrbpv/eKEcLFCpcteOHIhjacGtfDYHrbuDG+6BOZgdMp68ZUNeqIWAuNfJU5bdvENW7DtWaYNrVY/5DoHOSSy+/kvN+9b4ROdrD9rShERBz/HyPX2L5ckk0yVzLv1yInFC4cWcNh1R6k9jFdnyln5YH1RdwUPsLipIdKBUcBtusNBqaX3BEGtSNemX4Oq/ZC6yPf6RILt4eA2k3iuUNcgcQzdRbEVKopZ/NDTHS7W5WFOye8R440bbKDk+4NAUQSmbzmx8b2fzUts1IJX448YJYNxzK2AxAUoMUGGwdfxKw2riXjJDF95QTQ4isR6KWoqE+rxYRgnqU="
install: mvn -v
script: mvn -B -nsu verify jacoco:report
cache:
  directories:
    - $HOME/.m2
branches:
  except:
  - /^release\/.*$/
